image: node:alpine

variables:
  IMAGE: $DOCKERHUB_USERNAME/skyblue-app

stages:
  - build
  - test
  - deploy

# install dependencies 
install:
  stage: build
  script:
    - echo "Install run.."
    - npm install
  after_script:
    - ls -la

# build the application   
build:
  stage: build
  script:
    - echo "build run..."
    - npm install
  after_script:
    - ls -la
  needs:
    - install

# 🔨 Build image
build-docker-image:
  stage: build
  image: docker:29.3.0-cli
  services:
    - docker:29.3-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
   - echo "push docker image..."
   - docker build -t $IMAGE:$CI_COMMIT_SHORT_SHA .
   - docker push $IMAGE:$CI_COMMIT_SHORT_SHA
  after_script:
    - docker images
  needs:
    - build

# -----------------------
# 🧪 TEST STAGE
# -----------------------
test:
  stage: test
  script:
    - echo "Run tests here"

# -----------------------
# 🚀 DEPLOY TEMPLATE
# -----------------------
.deploy_template: &deploy_template
  stage: deploy
  image:
    name: lachlanevenson/k8s-helm:latest
    entrypoint: [""]
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - kubectl cluster-info
  script:
    - helm upgrade --install examen ./examen-chart \
        -f examen-chart/values-$ENV.yaml \
        -n $ENV \
        --set image.repository=$IMAGE \
        --set image.tag=$CI_COMMIT_SHORT_SHA \
        --create-namespace

# -----------------------
# 🚀 ENVIRONMENTS
# -----------------------

# 🚀 Deploy DEV
deploy_dev:
  <<: *deploy_template
  variables:
    ENV: dev
  only:
    - dev

#🚀 Deploy QA
deploy_qa:
  <<: *deploy_template
  variables:
    ENV: qa
  only:
    - qa

# 🚀 Deploy STAGING
deploy_staging:
  <<: *deploy_template
  variables:
    ENV: staging
  only:
    - staging

# 🚨 Deploy PROD (manual)
deploy_prod:
  <<: *deploy_template
  variables:
    ENV: prod
  when: manual
  only:
    - main
   